"""
run_simulations.py
------------------
Batch runner for the mosquito population dynamics C++ simulation engine.

Iterates over a grid of insertion ratios, equilibrium start dates, intervention
durations, and insertion frequencies; writes a per-run config CSV; and invokes
the compiled C++ executable for each parameter combination.

Environment variables (set in .env or shell):
    PROJECT_ROOT  – root directory of the project repository
    OUTPUT_DIR    – root directory where simulation outputs are written

Usage:
    python run_simulations.py
"""

import logging
import os
import subprocess
from pathlib import Path

import numpy as np
import pandas as pd
from dotenv import load_dotenv

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Config-CSV row indices
# Centralising magic numbers here makes future schema changes a single edit.
# ---------------------------------------------------------------------------
ROW = {
    "equilibrium_start_day":      18,
    "fixed_insertion_val":         29,
    "num_sims":                    22,
    "insertion_frequency":         14,
    "intervention_duration":       28,
    "temperature_file":            34,
    "carrying_capacity_dates":     35,
    "mcmc_file":                   36,
    "is_non_constant_scenario":    62,
    "non_constant_file":           63,
    "insertion_ratio":             64,
    "scale_factor":                65,
    "surveillance_file":           66,
    "random_seed":                 67,
    "output_folder":               27,
    "mcmc_output_placeholder":     55,
}

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
MONTH_NAMES = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]

# Day-of-year index for the first day of each month (non-leap year).
MONTH_START_DAYS = [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334]


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def is_leap_year(year: int) -> bool:
    """Return True if *year* is a leap year."""
    return (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)


def days_before_year(start_year: int, baseline_year: int = 2019) -> int:
    """
    Count the total number of days between *baseline_year* (inclusive) and
    *start_year* (exclusive), accounting for leap years.

    Parameters
    ----------
    start_year:
        The first year of the intervention period.
    baseline_year:
        The simulation's calendar epoch (default 2019).

    Returns
    -------
    int
        Total elapsed days from *baseline_year* up to (but not including)
        *start_year*.
    """
    return sum(
        366 if is_leap_year(y) else 365
        for y in range(baseline_year, start_year)
    )


def run_cpp_simulation(executable: Path, config_csv: Path) -> None:
    """
    Invoke the C++ mosquito simulation executable for a single parameter set.

    Parameters
    ----------
    executable:
        Absolute path to the compiled ``mosquito_sim.exe``.
    config_csv:
        Path to the per-run CSV config file generated by this script.

    Raises
    ------
    FileNotFoundError
        If *executable* does not exist on disk.
    subprocess.CalledProcessError
        Propagated from :func:`subprocess.run` when the executable exits
        with a non-zero return code.
    """
    if not executable.exists():
        raise FileNotFoundError(f"Executable not found: {executable}")

    # The C++ binary accepts the config path followed by three positional
    # placeholder arguments ("arg1", "arg2", "arg3").
    command = [str(executable), str(config_csv)]

    try:
        result = subprocess.run(command, capture_output=True, text=True, check=True)
        logger.info("Simulation finished: %s", config_csv.name)
        if result.stdout:
            logger.debug("stdout: %s", result.stdout.strip())
    except subprocess.CalledProcessError as exc:
        logger.error("Simulation failed for config: %s", config_csv)
        logger.error("Return code: %d", exc.returncode)
        logger.error("stderr:\n%s", exc.stderr)
        raise


def build_config_dataframe(
    template_df: pd.DataFrame,
    *,
    equilibrium_start_day: int,
    days_offset: int,
    insertion_ratio: float,
    insertion_frequency: int,
    intervention_duration: int,
    num_sims: int,
    output_folder: Path,
    temperature_file: Path,
    carrying_capacity_dates_file: Path,
    mcmc_file: Path,
    surveillance_file: Path,
    is_non_constant_scenario: int,
    scale_factor: float,
    random_seed: int,
) -> pd.DataFrame:
    """
    Return a copy of *template_df* with the relevant cells overwritten for
    one simulation run.

    All path arguments are converted to POSIX strings so the C++ executable
    receives forward-slash separators regardless of the host OS.
    """
    df = template_df.copy()

    df.iloc[ROW["equilibrium_start_day"], 1]   = equilibrium_start_day + days_offset
    df.iloc[ROW["fixed_insertion_val"], 1]      = 0
    df.iloc[ROW["num_sims"], 1]                 = num_sims
    df.iloc[ROW["insertion_frequency"], 1]      = insertion_frequency
    df.iloc[ROW["intervention_duration"], 1]    = intervention_duration

    df.iloc[ROW["temperature_file"], 1]          = str(temperature_file)
    df.iloc[ROW["carrying_capacity_dates"], 1]   = str(carrying_capacity_dates_file)
    df.iloc[ROW["mcmc_file"], 1]                 = str(mcmc_file)

    df.iloc[ROW["is_non_constant_scenario"], 1]  = is_non_constant_scenario
    df.iloc[ROW["non_constant_file"], 1]         = "not_required"
    df.iloc[ROW["insertion_ratio"], 1]           = insertion_ratio
    df.iloc[ROW["scale_factor"], 1]              = scale_factor
    df.iloc[ROW["surveillance_file"], 1]         = str(surveillance_file)
    df.iloc[ROW["random_seed"], 1]               = random_seed

    df.iloc[ROW["output_folder"], 1]             = str(output_folder) + "/"
    df.iloc[ROW["mcmc_output_placeholder"], 1]   = "/"

    return df


# ---------------------------------------------------------------------------
# Main experiment driver
# ---------------------------------------------------------------------------

def main() -> None:
    """Entry point: configure and launch the full simulation sweep."""

    # ------------------------------------------------------------------
    # Environment
    # ------------------------------------------------------------------
    load_dotenv()

    project_root = os.getenv("PROJECT_ROOT")
    if not project_root:
        raise EnvironmentError("PROJECT_ROOT environment variable is not set.")

    output_dir = os.getenv("OUTPUT_DIR")
    if not output_dir:
        raise EnvironmentError("OUTPUT_DIR environment variable is not set.")

    project_root = Path(project_root)
    output_dir   = Path(output_dir)

    # ------------------------------------------------------------------
    # Paths
    # ------------------------------------------------------------------
    inputs_folder = (
        project_root / "data" / "inputs" / "model_in" / "constant_release_trial_in"
    )

    temperature_file            = inputs_folder / "miami_2019_2023_temperature_celsius.csv"
    carrying_capacity_dates_file = inputs_folder / "Miami_carrying_capacity_dates.csv"
    mcmc_file                   = inputs_folder / "random_mcmc_carrying_capacity_100_vals.csv"
    surveillance_base_path      = (
        inputs_folder
        / "supporting_files"
        / "each_month_60_day_surveillance_100_sims_vals"
    )

    # Locate the compiled executable relative to this script file.
    script_dir  = Path(__file__).resolve().parent
    executable  = (script_dir / ".." / "build" / "Release" / "mosquito_sim.exe").resolve()

    # ------------------------------------------------------------------
    # Experiment parameters
    # ------------------------------------------------------------------
    intervention_start_year = 2021  # year to start the release of modified mosquito
    baseline_year           = 2019  # the simulation's calendar epoch (the year corresponding to day 0)
    num_sims                = 100   # number of stochastic simulations to run per parameter combination
    is_non_constant_scenario = 0    # 0 for constant, 1 for non-constant(adaptive) insertions scenario
    scale_factor            = 0.246  # collection factor to convert from number of mosquitoes to trap counts in the surveillance data
    random_seed             = 42    # random seed for reproducibility

    if is_non_constant_scenario:
        scenario_type_out_folder    = "adaptive_insertion_scenario"
    else:
        scenario_type_out_folder    = "constant_insertion_scenario"

    output_sub_folder = (
        f"test_2026_script_test_1/{scenario_type_out_folder}/"
        f"trails_starting_{intervention_start_year}/all_months_1_2_4_ratios"
    )
    sim_output_path = output_dir / output_sub_folder

    if sim_output_path.exists():
        raise FileExistsError(
            f"Output folder already exists – delete it or choose a new name:\n"
            f"  {sim_output_path}"
        )
    logger.info("Output directory: %s", sim_output_path)

    # Parameter sweep axes
    insertion_ratios        = np.round([1.0, 2.0, 4.0], decimals=1).tolist()
    equilibrium_start_dates = MONTH_START_DAYS          # one entry per month
    intervention_durations  = [180]                     # duration of the intervention in days (e.g., 180 days = 6 months)
    insertion_frequencies   = [7]                       # number of days between insertions (e.g., 7 = weekly)

    days_offset = days_before_year(intervention_start_year, baseline_year)
    logger.info(
        "Days before intervention start year %d (from %d): %d",
        intervention_start_year, baseline_year, days_offset,
    )

    # ------------------------------------------------------------------
    # Load config template
    # ------------------------------------------------------------------
    template_df = pd.read_csv(
        inputs_folder / "model_input_config.csv",
        header=None,
    )

    # ------------------------------------------------------------------
    # Sweep
    # ------------------------------------------------------------------
    total = (
        len(insertion_ratios)
        * len(equilibrium_start_dates)
        * len(intervention_durations)
        * len(insertion_frequencies)
    )
    completed = 0

    for ratio in insertion_ratios:
        for eq_day in equilibrium_start_dates:
            for duration in intervention_durations:
                for freq in insertion_frequencies:

                    month_name       = MONTH_NAMES[MONTH_START_DAYS.index(eq_day)]
                    surveillance_file = (
                        surveillance_base_path / f"{month_name}_surveillance.csv"
                    )

                    run_label   = f"{ratio}_{eq_day}_{freq}_{duration}"
                    run_folder  = sim_output_path / run_label
                    run_folder.mkdir(parents=True, exist_ok=False)

                    config_df = build_config_dataframe(
                        template_df,
                        equilibrium_start_day    = eq_day,
                        days_offset              = days_offset,
                        insertion_ratio          = ratio,
                        insertion_frequency      = freq,
                        intervention_duration    = duration,
                        num_sims                 = num_sims,
                        output_folder            = run_folder,
                        temperature_file         = temperature_file,
                        carrying_capacity_dates_file = carrying_capacity_dates_file,
                        mcmc_file                = mcmc_file,
                        surveillance_file        = surveillance_file,
                        is_non_constant_scenario = is_non_constant_scenario,
                        scale_factor             = scale_factor,
                        random_seed              = random_seed,
                    )

                    config_csv = run_folder / f"variables_{run_label}.csv"
                    config_df.to_csv(config_csv, index=False, header=False)

                    run_cpp_simulation(executable, config_csv)

                    completed += 1
                    logger.info("Progress: %d / %d", completed, total)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    main()